# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c7e576dd354177c788bf2ffd942b1ba4333643c63ce64882cff886e16d7c5c8eefdfa75d596de7f549d33aaee874d626c11742e64b27c4ca49eabbf185f5ffa

test:
  secret_key_base: 4636ae472f636890dc25b9abeb3afd16e6c980beabeb84d4794a0cbbc9ed9ee3ebba841eba25d197d52d0130fa5ab4530b945317ac45d523ec2aeee06700cefc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
